services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-local
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage_local:/qdrant/storage

volumes:
  qdrant_storage_local:
